permissions:
  contents: read # required to checkout the code from the repo

name: CI Pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v6

      - name: Install marmite 🫙
        run: |
          curl -OL https://github.com/rochacbruno/marmite/releases/download/0.2.5/marmite-0.2.5-x86_64-unknown-linux-gnu.tar.gz
          tar xvf marmite*.tar.gz

      - name: Build site 🏗️
        run: ./marmite . output -v

      - name: Install Backblaze B2 CLI
        run: |
          curl -OL https://github.com/Backblaze/B2_Command_Line_Tool/releases/latest/download/b2-linux
          chmod +x b2-linux

      - name: Upload site
        env: # Or as an environment variable
          B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
        run: |
          tar cvzf output.tar.gz output/
          ./b2-linux file upload cablespaghetti-website output.tar.gz site-$(date --iso-8601=seconds).tar.gz
          ./b2-linux file upload cablespaghetti-website output.tar.gz site-latest.tar.gz
